Repository tazama-lf/frms-coe-startup-lib, pull requests merged in 2024-10, with the labels that each got.

#97 feat: validate env
  __tests__/nats.test.ts
  package-lock.json
  package.json
  src/interfaces/iStartupConfig.ts
Labels: enhancement

#98 build: prepare 2.3.0-rc.1 release
  package-lock.json
  package.json
Labels: build

#99 fix: cater for optional vars
  package-lock.json
  package.json
  src/interfaces/iStartupConfig.ts
Labels: bug

#100 build: 2.3.0-rc.2
  package-lock.json
  package.json
Labels: build

#107 fix: manifest
  package-lock.json
  package.json
Labels: bug

#103 fix: Issue 227 Add Tazama into to LICENSE
  LICENSE
Labels: bug

#111 refactor: Bump lib
  package-lock.json
  package.json
  src/interfaces/iStartupConfig.ts
Labels: refactor

#112 refactor: bump lib version
  package-lock.json
  package.json
Labels: refactor

#117 feat: Bumped Version
  package-lock.json
  package.json
Labels: enhancement
