Repository tazama-lf/frms-coe-startup-lib, pull requests merged in 2024-07, with the labels that each got.

#61 feat: Enhancement to the release workflow
  .github/workflows/release.yml
Labels: enhancement

#64 build: bumped version for release 2.0.0
  package-lock.json
  package.json
Labels: build

#65 fix: Version bumping
  package-lock.json
  package.json
Labels: bug

#66 build: update lockfile
  package-lock.json
Labels: build

#68 fix: Lock file updated for Lib
  package-lock.json
Labels: bug
